<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProbeTfm Condition=" '$(ProbeTfm)' == '' ">net8.0</ProbeTfm>
    <TargetFramework>$(ProbeTfm)</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>probe</AssemblyName>
    <RootNamespace>probe</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
