import { expect, test, type Page } from '@playwright/test'
import { openWorkspace } from './app.js'
import { createHash } from 'node:crypto'

// A real, valid 1x1 grayscale PNG (Go's own internal/template/fixtures_test.go
// fixture, generated by Go's image/png encoder) — recognised and decodable by
// both the browser and Go, so this exercises the real command/decode path,
// not a synthetic stand-in.
const png1x1GrayBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAADklEQVR4nGJqAAQAAP//AIYAg0yeIEsAAAAASUVORK5CYII='
const png1x1GrayKey = createHash('sha256').update(Buffer.from(png1x1GrayBase64, 'base64')).digest('hex')

// Story 5.13's own instruction: this coverage MUST exercise the File System
// Access tier, not only the <input type="file"> fallback — commit eef7fbb is
// a measured in-repo instance of a receiver-binding defect that broke this
// tier alone, passed the whole unit suite, and survived the entire Epic 5
// Playwright gate. So, unlike most of this suite's other specs, this file
// does NOT disable window.showOpenFilePicker/showSaveFilePicker.
async function installNativePickers(page: Page): Promise<void> {
  await page.addInitScript((base64) => {
    const decoded = atob(base64)
    const numbers: number[] = []
    for (let index = 0; index < decoded.length; index++) numbers.push(decoded.charCodeAt(index))
    const imageBytes = new Uint8Array(numbers)
    const state = { writes: [] as Uint8Array[] }
    ;(window as unknown as { __folio8ImageE2E: typeof state }).__folio8ImageE2E = state
    const imageHandle = {
      name: 'logo.png',
      getFile: async () => new File([imageBytes.buffer as ArrayBuffer], 'logo.png', { type: 'image/png' }),
      createWritable: async () => ({ write: async () => undefined, close: async () => undefined }),
    }
    const templateHandle = {
      name: 'statement.folio',
      getFile: async () => new File([(state.writes.at(-1) ?? new Uint8Array()).buffer as ArrayBuffer], 'statement.folio', { type: 'application/json' }),
      createWritable: async () => ({ write: async (written: ArrayBuffer) => { state.writes.push(new Uint8Array(written)) }, close: async () => undefined }),
    }
    // Distinguish the image picker from the template picker by the accept
    // list the two capability tiers each declare (image/* vs application/json)
    // — this mock stands in for the OS file dialog, which makes exactly this
    // distinction for a real user.
    //
    // Finding 2 (review of 2026-08-29): these were plain arrow functions,
    // which have no `this` binding and so accept ANY receiver — reverting
    // capability.ts's `.bind(browser)` to eef7fbb's unbound-receiver defect
    // still passed this spec. A real browser's native picker brand-checks
    // its receiver and throws "Illegal invocation" when called unbound
    // (e.g. `const f = window.showOpenFilePicker; f()`), which is exactly
    // the failure mode eef7fbb shipped. Use `function` expressions that
    // reproduce that brand check, so an unbound receiver fails HERE the way
    // it fails in Chrome — the entire stated justification for this spec
    // existing under D-5.13.5.
    Object.assign(window, {
      showOpenFilePicker: function (
        this: unknown,
        options?: { types?: ReadonlyArray<{ accept?: Record<string, unknown> }> },
      ) {
        if (this !== window) {
          throw new TypeError("Failed to execute 'showOpenFilePicker' on 'Window': Illegal invocation")
        }
        const acceptsImage = options?.types?.[0]?.accept && 'image/png' in options.types[0].accept
        return Promise.resolve([acceptsImage ? imageHandle : templateHandle])
      },
      showSaveFilePicker: function (this: unknown) {
        if (this !== window) {
          throw new TypeError("Failed to execute 'showSaveFilePicker' on 'Window': Illegal invocation")
        }
        return Promise.resolve(templateHandle)
      },
    })
  }, png1x1GrayBase64)
}

test('the File System Access tier sets a local image through one committed command, paints it, survives save/reopen, and undo/redo restores the prior asset', async ({ page }) => {
  await installNativePickers(page)
  await openWorkspace(page)
  await expect(page.getByTestId('engine-snapshot')).toHaveText(/GO SNAPSHOT · REVISION 1/)

  const content = page.getByRole('region', { name: 'Content', exact: true })
  await page.getByRole('button', { name: 'Place Image' }).click()
  await content.press('Enter')
  const imageComponent = content.getByRole('button', { name: /image component/ })
  await expect(imageComponent).toHaveCount(1)
  await imageComponent.click()

  // AC2: the IMAGE section reports the CURRENT state straight from the
  // engine snapshot — here an unfilled box, because a placed image starts
  // with a null asset and waits for a file. getByText('IMAGE') alone is
  // a strict-mode collision (it substring/case-insensitively matches the
  // palette's "Place Image" caption, the identity row's "image" type text,
  // the honest-note identity string, and the "Choose image…" button all at
  // once) — scope to the PropertySection's own <p class="section-label">
  // and anchor the regex so only the literal section title matches.
  await expect(page.locator('p.section-label', { hasText: /^IMAGE$/ })).toBeVisible()
  await expect(page.getByText(/^No image chosen yet\./)).toBeVisible()
  await expect(imageComponent.locator('img.canvas-image-paint')).toHaveCount(0)
  const pickButton = page.getByRole('button', { name: 'Choose image…' })
  await expect(pickButton).toBeEnabled()

  // Select, choose a file, see it on the canvas (AC1/AC2/AC3). AC2 requires
  // this control to be KEYBOARD-operable, not merely focusable (Finding 15,
  // review of 2026-08-29) — a native <button> converts Enter into a real
  // 'click' event by browser construction, which jsdom's unit harness
  // cannot synthesise from a bare keydown (App.test.tsx notes this and
  // defers the activation half here). Focus it with Tab from the just-
  // selected component, then press Enter — a real OS-level key press, the
  // native browser behaviour AC2's "operable" promise actually rests on.
  const revisionBefore = await page.getByTestId('engine-snapshot').textContent()
  await pickButton.focus()
  await expect(pickButton).toBeFocused()
  await page.keyboard.press('Enter')
  await expect.poll(async () => page.getByTestId('engine-snapshot').textContent()).not.toBe(revisionBefore)
  await expect(page.getByText(`image/png · 1×1px · asset ${png1x1GrayKey.slice(0, 12)}…`, { exact: true })).toBeVisible()
  await expect(imageComponent.locator('img.canvas-image-paint')).toBeVisible()

  // Undo restores the prior state — the unfilled box; redo restores the pick.
  // Undo/Redo is pre-existing, story-independent behaviour: applyHistory's
  // setCurrentSnapshot(..., true) clears the local selection on EVERY
  // history navigation (deliberate — the footer note on the deselected
  // PAGE SETUP panel says as much), so the inspector always drops back to
  // "Component properties require a selection" first. Re-select the
  // component to observe the reverted/restored ENGINE state, which is
  // what AC4's undo/redo guarantee is actually about.
  const revisionAfterPick = await page.getByTestId('engine-snapshot').textContent()
  await page.getByRole('button', { name: /^Undo/ }).click()
  await expect.poll(async () => page.getByTestId('engine-snapshot').textContent()).not.toBe(revisionAfterPick)
  await imageComponent.click()
  await expect(page.getByText(/^No image chosen yet\./)).toBeVisible()
  await expect(page.getByText(`image/png · 1×1px · asset ${png1x1GrayKey.slice(0, 12)}…`, { exact: true })).toHaveCount(0)
  const revisionAfterUndo = await page.getByTestId('engine-snapshot').textContent()
  await page.getByRole('button', { name: /^Redo/ }).click()
  await expect.poll(async () => page.getByTestId('engine-snapshot').textContent()).not.toBe(revisionAfterUndo)
  await imageComponent.click()
  await expect(page.getByText(`image/png · 1×1px · asset ${png1x1GrayKey.slice(0, 12)}…`, { exact: true })).toBeVisible()

  // Preview: the canvas region is replaced and comes back without a crash.
  await page.getByRole('button', { name: 'PREVIEW' }).click()
  await expect(page.getByLabel('Canvas region')).toHaveCount(0)
  // STORY 13.5 — the preview heading's Return-to-Design button was removed; the
  // document bar's mode switch is the same `returnToDesign` and the only
  // in-page exit that remains.
  await page.getByRole('button', { name: 'DESIGN' }).click()
  await expect(page.getByLabel('Canvas region')).toBeVisible()

  // Save writes canonical bytes carrying the new asset under its real
  // SHA-256 key; reopening the SAME bytes shows the SAME identity again —
  // the asset embedded, never linked, surviving a full round trip.
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+S' : 'Control+S')
  await expect(page.getByText(/Saved locally as statement\.folio/)).toBeVisible()
  const written = await page.evaluate(() => {
    const state = (window as unknown as { __folio8ImageE2E: { writes: Uint8Array[] } }).__folio8ImageE2E
    return Array.from(state.writes.at(-1) ?? [])
  })
  const writtenText = Buffer.from(written).toString('utf8')
  expect(writtenText).toContain(`"${png1x1GrayKey}"`)

  await page.getByRole('button', { name: 'Open local template' }).click()
  await expect(page.locator('.document-name')).toHaveText('statement.folio')
  const reopenedImageComponent = content.getByRole('button', { name: /image component/ })
  await reopenedImageComponent.click()
  await expect(page.getByText(`image/png · 1×1px · asset ${png1x1GrayKey.slice(0, 12)}…`, { exact: true })).toBeVisible()
  await expect(reopenedImageComponent.locator('img.canvas-image-paint')).toBeVisible()
})

// Regression: an image component must be draggable on the canvas exactly
// like every other component type. Before this story, CanvasComponent
// painted the literal string 'Image' for an image component; AC3 replaced
// that with a real <img>, which is natively draggable in every browser
// unless told otherwise. Without draggable={false} on the <img> (and
// pointer-events: none on .canvas-image-paint, matching the
// .canvas-text-paint precedent), a real mouse-down-move-up sequence over
// the image starts the BROWSER's own native image drag instead of
// CanvasComponent's onPointerDown/onPointerMove/onPointerUp move handler —
// pointer capture is lost mid-gesture and the component never moves. This
// is why the drive here is page.mouse (real OS-level mouse events that can
// trigger a native dragstart), not page.getByRole(...).dragTo(...) or a
// synthetic pointer-event dispatch, either of which could pass without
// ever exercising the browser's native drag path this defect lives in.
test('a placed image component can be dragged on the canvas like any other component', async ({ page }) => {
  await installNativePickers(page)
  await openWorkspace(page)
  await expect(page.getByTestId('engine-snapshot')).toHaveText(/GO SNAPSHOT · REVISION 1/)

  const content = page.getByRole('region', { name: 'Content', exact: true })
  await page.getByRole('button', { name: 'Place Image' }).click()
  await content.press('Enter')
  const imageComponent = content.getByRole('button', { name: /image component/ })
  await expect(imageComponent).toHaveCount(1)
  // A placed box starts empty (its asset is null until the author chooses a
  // file), and this spec needs a real <img> to drive, so pick one first.
  await imageComponent.click()
  await page.getByRole('button', { name: 'Choose image…' }).click()
  await expect(imageComponent.locator('img.canvas-image-paint')).toBeVisible()

  const revisionBeforeDrag = await page.getByTestId('engine-snapshot').textContent()
  const before = await imageComponent.boundingBox()
  if (!before) throw new Error('placed image component was not painted')

  await page.mouse.move(before.x + before.width / 2, before.y + before.height / 2)
  await page.mouse.down()
  await page.mouse.move(before.x + before.width / 2 + 40, before.y + before.height / 2 + 30, { steps: 5 })
  await page.mouse.up()

  // The move must be COMMITTED (a new engine revision), not merely a local
  // visual nudge that the browser's native drag ghost would also produce.
  await expect.poll(async () => page.getByTestId('engine-snapshot').textContent()).not.toBe(revisionBeforeDrag)

  const after = await imageComponent.boundingBox()
  if (!after) throw new Error('dragged image component was not painted')
  // A native image drag would leave the element's own box exactly where it
  // started (the browser drags a ghost, not the element) and would not
  // advance the engine revision at all — so this assertion, combined with
  // the revision-change poll above, is what a hijacked drag cannot satisfy
  // either way.
  expect(Math.abs(after.x - before.x)).toBeGreaterThan(20)
  expect(Math.abs(after.y - before.y)).toBeGreaterThan(15)
})

// Finding 10 (review of 2026-08-29): the coverage audit found move was the
// only interaction ever exercised against the new <img> element — resize
// and zoom were never driven at all. The resize-handle's 24x24 hit target
// (App.css:62) sits partly over the box interior the <img> now occupies;
// this proves the handle still wins the hit test (DOM order plus
// pointer-events: none on .canvas-image-paint/.canvas-image-placeholder),
// and that the painted image's own box tracks both a committed resize and
// a zoom change against the projected rectangle — never a browser-computed
// fit (AC3).
test('a placed image component can be resized, and its painted box tracks both the resize and a zoom change', async ({ page }) => {
  await installNativePickers(page)
  await openWorkspace(page)
  await expect(page.getByTestId('engine-snapshot')).toHaveText(/GO SNAPSHOT · REVISION 1/)

  const content = page.getByRole('region', { name: 'Content', exact: true })
  await page.getByRole('button', { name: 'Place Image' }).click()
  await content.press('Enter')
  const imageComponent = content.getByRole('button', { name: /image component/ })
  await expect(imageComponent).toHaveCount(1)
  // A placed box starts empty (its asset is null until the author chooses a
  // file), and this spec needs a real <img> to drive, so pick one first.
  await imageComponent.click()
  await page.getByRole('button', { name: 'Choose image…' }).click()
  await expect(imageComponent.locator('img.canvas-image-paint')).toBeVisible()
  const paintedImage = imageComponent.locator('img.canvas-image-paint')
  // Selection controls live in the sheet overlay so band edges cannot crop
  // them. Match the exact component ID, avoiding the page boundary controls.
  const id = await imageComponent.getAttribute('data-component-id')
  const handle = page.getByRole('button', { name: `Resize ${id}`, exact: true })
  await expect(handle).toBeVisible()

  // Resize: drag the handle and confirm the COMMITTED box grew (a new
  // engine revision), and the painted <img> grew with it rather than
  // staying pinned to the old geometry. This is the interaction Finding 5
  // reached the owner through: without pointer-events: none on the paint
  // and its DOM position after the handle, a real mouse-down over the
  // overlapping region would hit the <img>, not the handle.
  const revisionBeforeResize = await page.getByTestId('engine-snapshot').textContent()
  const handleBox = await handle.boundingBox()
  const imageBefore = await paintedImage.boundingBox()
  if (!handleBox || !imageBefore) throw new Error('placed image component was not painted')
  await page.mouse.move(handleBox.x + handleBox.width / 2, handleBox.y + handleBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(handleBox.x + handleBox.width / 2 + 50, handleBox.y + handleBox.height / 2 + 40, { steps: 5 })
  await page.mouse.up()
  await expect.poll(async () => page.getByTestId('engine-snapshot').textContent()).not.toBe(revisionBeforeResize)
  const imageAfterResize = await paintedImage.boundingBox()
  if (!imageAfterResize) throw new Error('resized image component was not painted')
  // The painted image's own box must have moved/grown too — a stale paint
  // pinned to the pre-resize rectangle is exactly the "coverage was never
  // re-derived for the new DOM element" defect this test exists to catch.
  expect(imageAfterResize.width).not.toBe(imageBefore.width)

  // Zoom: AC3 says the draw rectangle is "mapped through the existing zoom
  // rule". Step zoom in once and confirm the painted image's own box
  // scales — never held at a browser-computed, zoom-blind size.
  await page.getByRole('button', { name: 'Zoom in' }).click()
  await expect(page.getByLabel('Canvas zoom')).toHaveText('110%')
  await expect.poll(async () => (await paintedImage.boundingBox())?.width).not.toBe(imageAfterResize.width)
})
