package folio8

import (
	"bytes"
	"encoding/base64"
	"errors"
	"testing"

	"github.com/panitw/folio8/folio-go/internal/designer"
	"github.com/panitw/folio8/folio-go/internal/template"
)

// png1x1Gray mirrors internal/template/fixtures_test.go's unknownKeysFixture
// asset: a real, valid 1x1 grayscale PNG (generated by Go's image/png
// encoder). It gives this file a THIRD distinct, valid picture alongside
// png3x2RGB and jpeg4x4Bytes() — png2x2Alpha is deliberately NOT usable
// here, since it is internal/template's own colour-type-6 REJECTION
// fixture (an image this library explicitly refuses, AC12), not a valid
// asset.
func png1x1Gray() []byte {
	decoded, err := base64.StdEncoding.DecodeString("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAADklEQVR4nGJqAAQAAP//AIYAg0yeIEsAAAAASUVORK5CYII=")
	if err != nil {
		panic(err)
	}
	return decoded
}

// setAssetCommand builds the opaque setComponentAsset command JSON this
// story adds (AC1, D-5.13.1): a closed, two-value payload (raw bytes plus
// declared media type) targeting exactly one component id.
func setAssetCommand(id, mediaType string, data []byte) []byte {
	return []byte(`{"kind":"setComponentAsset","version":1,"id":"` + id + `","mediaType":"` + mediaType + `","data":"` + base64Std(data) + `"}`)
}

func twoImageTemplateJSON(keyA string, dataA []string, mtA string, keyB string, dataB []string, mtB string) string {
	return `{
  "assets": {
    "` + keyA + `": {"data": [` + quoteJoin(dataA) + `], "mediaType": "` + mtA + `"},
    "` + keyB + `": {"data": [` + quoteJoin(dataB) + `], "mediaType": "` + mtB + `"}
  },
  "bands": {
    "content": {"elements": [
      {"id": "e1", "type": "image", "asset": "` + keyA + `", "x": 10, "y": 20, "width": 72000, "height": 48000},
      {"id": "e2", "type": "image", "asset": "` + keyB + `", "x": 10, "y": 80, "width": 72000, "height": 48000}
    ]},
    "pageFooter": {"elements": [], "height": 20},
    "pageHeader": {"elements": [], "height": 20}
  },
  "fonts": {},
  "locale": "en",
  "nextId": 3,
  "page": {"margin": {"bottom": 36, "left": 36, "right": 36, "top": 36}, "orientation": "portrait", "size": "A4"},
  "utcOffset": "+00:00",
  "version": "1.0"
}`
}

// twoImageTemplateJSONWithOrphan is twoImageTemplateJSON plus a THIRD asset,
// keyC, that no element references — neither before nor after the command
// under test repoints e1. It exists only for
// TestSetComponentAssetNeverSweepsAnUnrelatedOrphan (Finding 1, review of
// 2026-08-29): twoImageTemplateJSON's keyB is referenced by e2, so a test
// built only from it cannot distinguish "collect only what this mutation
// orphaned" (D-5.13.3) from a document-wide sweep — both leave a
// still-referenced keyB alone. keyC, genuinely unreferenced from the start,
// is the fixture RP-11's positive control describes: a document may legally
// carry an asset nothing points at, and this command must never sweep it
// just because it mutated a different element. keyC's media type is
// deliberately unrecognised (image/webp over non-image bytes), echoing
// render_image_test.go's TestRenderUnrecognisedMediaTypeErrorsOnlyWhenDrawn
// so this test doubles as an in-command instance of that positive control.
func twoImageTemplateJSONWithOrphan(keyA string, dataA []string, mtA string, keyB string, dataB []string, mtB string, keyC string, dataC []string, mtC string) string {
	return `{
  "assets": {
    "` + keyA + `": {"data": [` + quoteJoin(dataA) + `], "mediaType": "` + mtA + `"},
    "` + keyB + `": {"data": [` + quoteJoin(dataB) + `], "mediaType": "` + mtB + `"},
    "` + keyC + `": {"data": [` + quoteJoin(dataC) + `], "mediaType": "` + mtC + `"}
  },
  "bands": {
    "content": {"elements": [
      {"id": "e1", "type": "image", "asset": "` + keyA + `", "x": 10, "y": 20, "width": 72000, "height": 48000},
      {"id": "e2", "type": "image", "asset": "` + keyB + `", "x": 10, "y": 80, "width": 72000, "height": 48000}
    ]},
    "pageFooter": {"elements": [], "height": 20},
    "pageHeader": {"elements": [], "height": 20}
  },
  "fonts": {},
  "locale": "en",
  "nextId": 3,
  "page": {"margin": {"bottom": 36, "left": 36, "right": 36, "top": 36}, "orientation": "portrait", "size": "A4"},
  "utcOffset": "+00:00",
  "version": "1.0"
}`
}

func quoteJoin(values []string) string {
	out := ""
	for i, v := range values {
		if i > 0 {
			out += ","
		}
		out += `"` + v + `"`
	}
	return out
}

// findElementByID is a test-only lookup across every band, used to assert
// on the repointed element's Asset field after a command.
func findElementByID(t *testing.T, tpl *Template, id string) template.Element {
	t.Helper()
	for _, elements := range [][]template.Element{tpl.doc.Bands.PageHeader.Elements, tpl.doc.Bands.Content.Elements, tpl.doc.Bands.PageFooter.Elements} {
		for _, el := range elements {
			if string(el.ID) == id {
				return el
			}
		}
	}
	t.Fatalf("element %s not found", id)
	return template.Element{}
}

// TestSetComponentAssetInstallsAndRepointsInOneTransaction proves AC1's
// core: a successful command inserts the content-addressed asset (keyed by
// the SHA-256 of the DECODED bytes), repoints the element, orphan-collects
// the previous key (nothing else referenced it), and does so as one
// serialize/reparse/project transaction, surviving round-trip.
func TestSetComponentAssetInstallsAndRepointsInOneTransaction(t *testing.T) {
	oldKey := sha256Hex(png3x2RGB)
	tpl, err := ParseTemplate([]byte(imageTemplateJSON(oldKey, wrap76(png3x2RGB), "image/png", 72000, 48000)))
	if err != nil {
		t.Fatal(err)
	}
	newKey := sha256Hex(png1x1Gray())
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/png", png1x1Gray())); err != nil {
		t.Fatalf("setComponentAsset: %v", err)
	}
	if _, ok := tpl.doc.Assets[newKey]; !ok {
		t.Fatalf("new asset key %s was not installed", newKey)
	}
	if _, ok := tpl.doc.Assets[oldKey]; ok {
		t.Fatalf("previous asset key %s should have been orphan-collected", oldKey)
	}
	el := findElementByID(t, tpl, "e1")
	if !el.Asset.Set || el.Asset.Value != newKey {
		t.Fatalf("element asset = %#v, want %s", el.Asset, newKey)
	}
	canonical, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	reparsed, err := ParseTemplate(canonical)
	if err != nil {
		t.Fatal(err)
	}
	again, err := SerializeTemplate(reparsed)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(canonical, again) {
		t.Fatal("Parse(Serialize(d)) != d after setComponentAsset")
	}
}

// TestSetComponentAssetDedupsIdenticalBytes proves AC1's dedup clause: the
// same picture chosen for two elements stores one asset and two references.
func TestSetComponentAssetDedupsIdenticalBytes(t *testing.T) {
	keyA, keyB := sha256Hex(png3x2RGB), sha256Hex(png1x1Gray())
	tpl, err := ParseTemplate([]byte(twoImageTemplateJSON(keyA, wrap76(png3x2RGB), "image/png", keyB, wrap76(png1x1Gray()), "image/png")))
	if err != nil {
		t.Fatal(err)
	}
	shared := jpeg4x4Bytes()
	sharedKey := sha256Hex(shared)
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/jpeg", shared)); err != nil {
		t.Fatalf("set e1: %v", err)
	}
	if _, err := applyComponentCommand(tpl, setAssetCommand("e2", "image/jpeg", shared)); err != nil {
		t.Fatalf("set e2: %v", err)
	}
	if len(tpl.doc.Assets) != 1 {
		t.Fatalf("assets map = %#v, want exactly one entry after dedup", tpl.doc.Assets)
	}
	if _, ok := tpl.doc.Assets[sharedKey]; !ok {
		t.Fatalf("shared asset key %s missing", sharedKey)
	}
	e1, e2 := findElementByID(t, tpl, "e1"), findElementByID(t, tpl, "e2")
	if e1.Asset.Value != sharedKey || e2.Asset.Value != sharedKey {
		t.Fatalf("e1/e2 asset = %q/%q, want both %s", e1.Asset.Value, e2.Asset.Value, sharedKey)
	}
}

// TestSetComponentAssetRefusesUnrecognisedMediaTypeAtTheCommand proves AC1's
// central refusal clause: a media type this version cannot decode is
// refused AT THE COMMAND with a located diagnostic and never enters the
// document — decodeAssets (the load-time contract) must never be the thing
// that catches it.
func TestSetComponentAssetRefusesUnrecognisedMediaTypeAtTheCommand(t *testing.T) {
	key := sha256Hex(png3x2RGB)
	tpl, err := ParseTemplate([]byte(imageTemplateJSON(key, wrap76(png3x2RGB), "image/png", 72000, 48000)))
	if err != nil {
		t.Fatal(err)
	}
	before, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	garbage := []byte("not any recognised format")
	_, err = applyComponentCommand(tpl, setAssetCommand("e1", "image/webp", garbage))
	if err == nil {
		t.Fatal("expected an unrecognised-media-type command to be refused")
	}
	var cerr *designer.ComponentCommandError
	if !errors.As(err, &cerr) {
		t.Fatalf("error %v is not a located ComponentCommandError", err)
	}
	if cerr.ElementID != "e1" {
		t.Fatalf("diagnostic elementID = %q, want e1", cerr.ElementID)
	}
	after, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("a rejected command must leave canonical bytes unchanged")
	}
	garbageKey := sha256Hex(garbage)
	if _, ok := tpl.doc.Assets[garbageKey]; ok {
		t.Fatal("a rejected command must never half-insert an asset")
	}
}

// TestSetComponentAssetRefusesNonImageTarget proves AC1's target-eligibility
// clause: an image element and nothing else.
func TestSetComponentAssetRefusesNonImageTarget(t *testing.T) {
	tpl := componentTemplate(t)
	before, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	// worked-example.json's first content element is a table (e1); reuse it
	// as a definitely-non-image target.
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/png", png3x2RGB)); err == nil {
		t.Fatal("expected setComponentAsset to refuse a non-image target")
	}
	after, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("a rejected command must leave canonical bytes unchanged")
	}
}

// TestSetComponentAssetRefusesOversizedPayload proves D-5.13.4's host-memory
// bound is enforced in Go, not merely relied on from the transport.
func TestSetComponentAssetRefusesOversizedPayload(t *testing.T) {
	key := sha256Hex(png3x2RGB)
	tpl, err := ParseTemplate([]byte(imageTemplateJSON(key, wrap76(png3x2RGB), "image/png", 72000, 48000)))
	if err != nil {
		t.Fatal(err)
	}
	oversized := make([]byte, maxComponentAssetBytes+1)
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/png", oversized)); err == nil {
		t.Fatal("expected an oversized asset to be refused")
	}
}

// TestSetComponentAssetChoosingSamePictureIsIdempotentAtTheEngineLayer
// exercises the wasm.Engine-level bytes.Equal short-circuit precondition:
// setComponentAsset must produce byte-identical canonical output when the
// element already names that exact key, so the outer engine transaction can
// recognise "nothing changed" and not advance revision/undo. Proven here by
// asserting canonical bytes are unchanged; wasm package tests prove the
// engine-level non-advance.
func TestSetComponentAssetChoosingSamePictureIsIdempotentAtTheEngineLayer(t *testing.T) {
	key := sha256Hex(png3x2RGB)
	tpl, err := ParseTemplate([]byte(imageTemplateJSON(key, wrap76(png3x2RGB), "image/png", 72000, 48000)))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/png", png3x2RGB)); err != nil {
		t.Fatalf("re-choosing the same picture unexpectedly failed: %v", err)
	}
	before, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/png", png3x2RGB)); err != nil {
		t.Fatalf("re-choosing the same picture unexpectedly failed: %v", err)
	}
	after, err := SerializeTemplate(tpl)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("re-choosing the same picture must leave canonical bytes unchanged")
	}
}

// TestSetComponentAssetReplacingRepeatedlyLeavesExactlyOneAsset proves AC4's
// headline example: replacing a logo ten times leaves one asset, not eleven.
func TestSetComponentAssetReplacingRepeatedlyLeavesExactlyOneAsset(t *testing.T) {
	key := sha256Hex(png3x2RGB)
	tpl, err := ParseTemplate([]byte(imageTemplateJSON(key, wrap76(png3x2RGB), "image/png", 72000, 48000)))
	if err != nil {
		t.Fatal(err)
	}
	pictures := [][]byte{png1x1Gray(), jpeg4x4Bytes(), png1x1Gray(), jpeg4x4Bytes()}
	mediaTypes := []string{"image/png", "image/jpeg", "image/png", "image/jpeg"}
	for i, picture := range pictures {
		if _, err := applyComponentCommand(tpl, setAssetCommand("e1", mediaTypes[i], picture)); err != nil {
			t.Fatalf("replace #%d: %v", i, err)
		}
	}
	if len(tpl.doc.Assets) != 1 {
		t.Fatalf("assets map = %#v, want exactly one entry after repeated replacement", tpl.doc.Assets)
	}
}

// TestSetComponentAssetNeverSweepsAnUnrelatedOrphan proves D-5.13.3: a
// document may legally carry an asset that nothing references, and this
// command must never sweep it away just because it mutated a different
// element.
func TestSetComponentAssetNeverSweepsAnUnrelatedOrphan(t *testing.T) {
	garbage := []byte("not any recognised format, and no element ever names it")
	keyA, keyB, keyC := sha256Hex(png3x2RGB), sha256Hex(png1x1Gray()), sha256Hex(garbage)
	tpl, err := ParseTemplate([]byte(twoImageTemplateJSONWithOrphan(
		keyA, wrap76(png3x2RGB), "image/png",
		keyB, wrap76(png1x1Gray()), "image/png",
		keyC, wrap76(garbage), "image/webp",
	)))
	if err != nil {
		t.Fatal(err)
	}
	// Repoint e1 away from keyA onto a fresh picture; e2 (and keyB) are
	// untouched, and keyC is referenced by NOTHING, before or after —
	// the genuine orphan a document-wide sweep would also catch. keyA
	// must vanish (this command DID just orphan it); keyB and keyC must
	// both remain. A document-wide sweep (D-5.13.3's rejected option)
	// would delete keyC too, since nothing references it — that is
	// exactly the defect this fixture must catch and the pre-fix
	// version of this test could not: with only keyA/keyB, a sweep and
	// a scoped collection are indistinguishable, since keyB was always
	// referenced by e2 regardless of which policy runs.
	if _, err := applyComponentCommand(tpl, setAssetCommand("e1", "image/jpeg", jpeg4x4Bytes())); err != nil {
		t.Fatal(err)
	}
	if _, ok := tpl.doc.Assets[keyB]; !ok {
		t.Fatal("an asset this command never touched must never be swept")
	}
	if _, ok := tpl.doc.Assets[keyC]; !ok {
		t.Fatal("a genuinely unreferenced asset (RP-11's positive control) must survive: this command is not a document-wide sweep (D-5.13.3)")
	}
	if _, ok := tpl.doc.Assets[keyA]; ok {
		t.Fatal("the previous key this command just orphaned must be collected")
	}
}
