package folio8

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"

	"github.com/panitw/folio8/folio-go/internal/designer"
	"github.com/panitw/folio8/folio-go/internal/expr"
)

// standInShell wraps content-band element JSON in the smallest document
// that renders. Most fixtures only need the content band; the ones that
// exercise the band WALK use standInBandShell directly.
func standInShell(elements string) string { return standInBandShell("", elements, "") }

// standInBandShell populates all three bands. It exists because a shell
// that hardcoded empty pageHeader/pageFooter arrays made two thirds of
// the band walk unverifiable: reducing the walk to Bands.Content alone
// left the whole package green.
func standInBandShell(header, content, footer string) string {
	return fmt.Sprintf(`{
  "assets": {},
  "bands": {
    "content": {"elements": [%s]},
    "pageFooter": {"elements": [%s], "height": 20},
    "pageHeader": {"elements": [%s], "height": 20}
  },
  "fonts": {"body": ["Noto Sans"]},
  "locale": "en",
  "nextId": 20,
  "page": {"margin": {"bottom": 36, "left": 36, "right": 36, "top": 36}, "orientation": "portrait", "size": "A4"},
  "utcOffset": "+00:00",
  "version": "1.0"
}
`, content, footer, header)
}

// standInTextElement is one text element carrying value verbatim. The
// value is JSON-quoted here rather than by the caller so a pattern
// literal's own quotes survive.
func standInTextElement(id, value string) string {
	return fmt.Sprintf(`{"id": %q, "type": "text", "x": 0, "y": 0, "width": 460, "height": 20, "value": %q, "style": {"fontFamily": "body", "fontSize": 12}}`, id, value)
}

func standInTemplate(t *testing.T, elements string) *Template {
	t.Helper()
	tpl, err := ParseTemplate([]byte(standInShell(elements)))
	if err != nil {
		t.Fatalf("presence precondition: the fixture template does not parse: %v", err)
	}
	return tpl
}

func standInBytes(t *testing.T, tpl *Template) []byte {
	t.Helper()
	out, err := standInData(tpl)
	if err != nil {
		t.Fatalf("StandInData: %v", err)
	}
	return out
}

// TestStandInRulesCoverTheEngineFunctionRegistry is THE exhaustiveness
// gate, ported from internal/expr's
// TestImplementedEntriesMatchEvalCallSwitch: set equality in BOTH
// directions between the generator's per-function rules and the engine's
// own registry, with NO function name restated anywhere in this test.
//
// Adding a ninth function to internal/expr's closed table without a
// matching stand-in rule reds this, naming that function.
func TestStandInRulesCoverTheEngineFunctionRegistry(t *testing.T) {
	engineNames := map[string]bool{}
	for _, name := range expr.LegalFunctionNames() {
		engineNames[name] = true
	}
	ruleNames := map[string]bool{}
	for _, name := range slices.Sorted(maps.Keys(standInFunctionRules)) {
		ruleNames[name] = true
	}

	for _, name := range slices.Sorted(maps.Keys(engineNames)) {
		if !ruleNames[name] {
			t.Errorf("%s: the engine's function registry declares this, but the stand-in generator has no value-kind rule for it", name)
		}
	}
	for _, name := range slices.Sorted(maps.Keys(ruleNames)) {
		if !engineNames[name] {
			t.Errorf("%s: the stand-in generator has a rule for this, but the engine's function registry has no such function", name)
		}
	}
	// Presence precondition (D-000.9): an empty extraction on either
	// side would make both comparisons above pass vacuously.
	if len(engineNames) == 0 || len(ruleNames) == 0 {
		t.Fatalf("presence precondition: engine names %d, generator rules %d — a zero on either side passes vacuously", len(engineNames), len(ruleNames))
	}
}

// TestStandInDocumentIsAcceptedByEveryFunction is the round trip: for each
// legal function, a real template using it is generated for, rendered with
// the generated bytes, and required to SUCCEED. The engine is the judge of
// whether the stand-in is legal, not this test's opinion of it.
//
// The fixture set is itself checked against the engine's registry, so a
// ninth function reds here too rather than being silently unexercised.
func TestStandInDocumentIsAcceptedByEveryFunction(t *testing.T) {
	// Each entry is one text-element value that uses the named function
	// on a path the generator must supply. sum/count return numbers; a
	// bare number would print as its exact decimal, but both stay wrapped
	// in formatNumber so that function's operand path is exercised too.
	fixtures := map[string]string{
		"sum":          `Total {{formatNumber(sum(ledger.amount), "0.00")}}`,
		"count":        `Rows {{formatNumber(count(ledger), "0")}}`,
		"avg":          `Mean {{avg(ledger.amount)}}`,
		"upper":        `Loud {{upper(customer.name)}}`,
		"lower":        `Quiet {{lower(customer.name)}}`,
		"formatNumber": `Money {{formatNumber(invoice.total, "#,##0.00")}}`,
		"formatDate":   `Dated {{formatDate(invoice.issued, "yyyy-MM-dd")}}`,
		"if":           `Flagged {{if(flags.vip, "yes", "no")}}`,
	}
	if missing := slices.Sorted(maps.Keys(fixtures)); len(missing) == 0 {
		t.Fatal("presence precondition: no round-trip fixtures declared")
	}
	for _, name := range expr.LegalFunctionNames() {
		if _, ok := fixtures[name]; !ok {
			t.Fatalf("%s: the engine declares this function and no round-trip fixture exercises it", name)
		}
	}
	for _, name := range slices.Sorted(maps.Keys(fixtures)) {
		t.Run(name, func(t *testing.T) {
			tpl := standInTemplate(t, standInTextElement("e1", fixtures[name]))
			data := standInBytes(t, tpl)
			if _, err := Render(tpl, Data(data), nil, testShippedFontSet()); err != nil {
				t.Fatalf("the stand-in document %s was refused by Render: %v", data, err)
			}
		})
	}
}

// TestStandInScalarBindingRendersAsNothing pins the story's second
// acceptance criterion against a LITERAL expected document, never against
// a value read back out of the generator (D-11.2.2, D-11.2.8).
func TestStandInScalarBindingRendersAsNothing(t *testing.T) {
	tpl, err := ParseTemplate(standInReadFile(t, "testdata/example/first-pdf.folio"))
	if err != nil {
		t.Fatalf("presence precondition: the shipped example does not parse: %v", err)
	}
	got := standInBytes(t, tpl)
	if string(got) != `{"customer":{"name":""}}` {
		t.Fatalf("stand-in document = %s, want {\"customer\":{\"name\":\"\"}}", got)
	}
	standIn, err := Render(tpl, Data(got), nil, testShippedFontSet())
	if err != nil {
		t.Fatalf("the stand-in render failed: %v", err)
	}
	// AND THE PAGE IS THE PAGE AN EMPTY VALUE PRODUCES. Rendering the
	// same template against a hand-written document whose one bound path
	// is the empty string must produce the same bytes — which is what
	// "renders as nothing at all" means, stated against a literal rather
	// than against the generator's own output.
	empty, err := Render(tpl, Data(`{"customer":{"name":""}}`), nil, testShippedFontSet())
	if err != nil {
		t.Fatalf("the literal empty-string render failed: %v", err)
	}
	if !bytes.Equal(standIn.Bytes, empty.Bytes) {
		t.Fatal("the stand-in render differs from the render of a literal empty string — the bound path did not render as nothing")
	}
}

// TestAbsentDataStillFailsWithTheLocatedBindingError is the story's
// central promise and gets its own pin: nothing here changes what Render
// does when data is genuinely ABSENT.
func TestAbsentDataStillFailsWithTheLocatedBindingError(t *testing.T) {
	tpl, err := ParseTemplate(standInReadFile(t, "testdata/example/first-pdf.folio"))
	if err != nil {
		t.Fatalf("presence precondition: the shipped example does not parse: %v", err)
	}
	_, rerr := Render(tpl, Data(`{}`), nil, testShippedFontSet())
	if rerr == nil {
		t.Fatal("Render succeeded with absent data — the located BINDING_PATH_ABSENT Error is this story's central invariant")
	}
	var renderErr *RenderError
	if !errors.As(rerr, &renderErr) {
		t.Fatalf("Render returned %T, not a *RenderError carrying a located Diagnostic: %v", rerr, rerr)
	}
	if renderErr.Diagnostic.Code != DiagCodeBindingPathAbsent {
		t.Fatalf("diagnostic code = %q, want %q", renderErr.Diagnostic.Code, DiagCodeBindingPathAbsent)
	}
	if renderErr.Diagnostic.ElementID == "" {
		t.Fatal("the Error lost its element location")
	}
	if !strings.Contains(renderErr.Diagnostic.Message, "customer.name") {
		t.Fatalf("the Error no longer names the absent path: %s", renderErr.Diagnostic.Message)
	}
}

// TestStandInCollectionIsEmptyAndRowScopeIsNeverEvaluated covers the
// bound-table row of the matrix. The stand-in collection is [], the table
// renders header-only, and the proof that no row exists is that the page
// is byte-identical to the page a hand-written empty collection produces.
func TestStandInCollectionIsEmptyAndRowScopeIsNeverEvaluated(t *testing.T) {
	table := `{"id": "e1", "type": "table", "x": 0, "y": 0, "bind": "transactions[]", "headerHeight": 12,
	  "style": {"fontFamily": "body", "fontSize": 9},
	  "columns": [
	    {"id": "e2", "label": "Date", "width": 120, "bind": "{{row.date}}"},
	    {"id": "e3", "label": "Amount", "width": 120, "bind": "{{formatNumber(row.amount, \"#,##0.00\")}}", "footer": "avg"}
	  ]}`
	tpl := standInTemplate(t, table)
	got := standInBytes(t, tpl)
	// THE RENDER IS ASSERTED BEFORE THE LITERAL, DELIBERATELY. [] is
	// load-bearing rather than incidental: with even one row in the
	// collection the row scope IS evaluated, and this template's column
	// bindings — for which no stand-in exists, and deliberately so — then
	// fail the render outright. Asserting the document text first would
	// red on the spelling and never reach the consequence that makes the
	// spelling matter.
	result, err := Render(tpl, Data(got), nil, testShippedFontSet())
	if err != nil {
		t.Fatalf("the stand-in table render failed: %v", err)
	}
	if string(got) != `{"transactions":[]}` {
		t.Fatalf("stand-in document = %s, want {\"transactions\":[]}", got)
	}
	explicit, err := Render(tpl, Data(`{"transactions":[]}`), nil, testShippedFontSet())
	if err != nil {
		t.Fatalf("the literal empty-collection render failed: %v", err)
	}
	if !bytes.Equal(result.Bytes, explicit.Bytes) {
		t.Fatal("the stand-in table render differs from a literal empty collection — the table did not render header-only")
	}
	// The engine's own empty-average Warning is SHOWN, not suppressed:
	// the avg footer over the empty stand-in collection is exactly the
	// case CodeEmptyAverage exists for.
	found := false
	for _, diagnostic := range result.Diagnostics {
		if diagnostic.Code == DiagCodeEmptyAverage {
			found = true
		}
	}
	if !found {
		t.Fatalf("the avg footer over the empty stand-in collection produced no %s Warning: %+v", DiagCodeEmptyAverage, result.Diagnostics)
	}
}

// TestStandInSharedContextsIntersect covers the two multi-context rows of
// the matrix: the pair that HAS a common value, and the pair that does
// not.
func TestStandInSharedContextsIntersect(t *testing.T) {
	t.Run("text and visibleIf share null", func(t *testing.T) {
		elements := standInTextElement("e1", "VIP: {{flags.vip}}") +
			`, {"id": "e2", "type": "rect", "x": 0, "y": 40, "width": 100, "height": 10, "visibleIf": "flags.vip"}`
		tpl := standInTemplate(t, elements)
		got := standInBytes(t, tpl)
		if string(got) != `{"flags":{"vip":null}}` {
			t.Fatalf("stand-in document = %s, want {\"flags\":{\"vip\":null}}", got)
		}
		result, err := Render(tpl, Data(got), nil, testShippedFontSet())
		if err != nil {
			t.Fatalf("the shared-null render failed: %v", err)
		}
		// D-3.2.3: a null condition hides the element SILENTLY — no
		// diagnostic at all.
		if len(result.Diagnostics) != 0 {
			t.Fatalf("a null visibility condition emitted diagnostics: %+v", result.Diagnostics)
		}
	})

	// A number in text prints as its exact decimal (2026-09-13), so text
	// and formatNumber now share the zero stand-in and preview renders.
	t.Run("text and formatNumber share zero", func(t *testing.T) {
		elements := standInTextElement("e1", `Raw {{invoice.total}} formatted {{formatNumber(invoice.total, "0.00")}}`)
		tpl := standInTemplate(t, elements)
		got := standInBytes(t, tpl)
		if string(got) != `{"invoice":{"total":0}}` {
			t.Fatalf("stand-in document = %s, want {\"invoice\":{\"total\":0}}", got)
		}
		if _, err := Render(tpl, Data(got), nil, testShippedFontSet()); err != nil {
			t.Fatalf("the shared-zero render failed: %v", err)
		}
	})

	t.Run("text and a direct divisor share one", func(t *testing.T) {
		elements := standInTextElement("e1", `{{d}} {{10 / d}}`)
		tpl := standInTemplate(t, elements)
		got := standInBytes(t, tpl)
		if string(got) != `{"d":1}` {
			t.Fatalf("stand-in document = %s, want {\"d\":1}", got)
		}
		if _, err := Render(tpl, Data(got), nil, testShippedFontSet()); err != nil {
			t.Fatalf("the shared-one render failed: %v", err)
		}
	})

	t.Run("text and visibleIf and formatNumber share nothing", func(t *testing.T) {
		elements := standInTextElement("e1", `Raw {{invoice.total}} formatted {{formatNumber(invoice.total, "0.00")}}`) +
			`, {"id": "e2", "type": "rect", "x": 0, "y": 40, "width": 100, "height": 10, "visibleIf": "invoice.total"}`
		tpl := standInTemplate(t, elements)
		_, err := standInData(tpl)
		if err == nil {
			t.Fatal("StandInData produced a document for a path whose contexts share no legal value — it must refuse, never mangle")
		}
		message := err.Error()
		for _, want := range []string{`"invoice.total"`, "a text binding", "formatNumber()'s operand", "a visibility condition"} {
			if !strings.Contains(message, want) {
				t.Fatalf("the refusal does not name %q: %s", want, message)
			}
		}
	})
}

// TestStandInDocumentIsByteDeterministic generates the same template's
// stand-in twice, from two independently parsed templates, and requires
// the bytes to match. The fixture carries many sibling paths so a map
// iteration leaking into the output would show up as an ordering
// difference rather than by luck.
func TestStandInDocumentIsByteDeterministic(t *testing.T) {
	elements := standInTextElement("e1", `{{alpha.one}} {{bravo.two}} {{charlie.three}} {{delta.four}} {{echo.five}} {{foxtrot.six}} {{golf.seven}} {{hotel.eight}}`)
	first := standInBytes(t, standInTemplate(t, elements))
	second := standInBytes(t, standInTemplate(t, elements))
	if !bytes.Equal(first, second) {
		t.Fatalf("two generations differ:\n%s\n%s", first, second)
	}
	if !strings.Contains(string(first), `"alpha"`) {
		t.Fatalf("presence precondition: the determinism fixture produced no paths: %s", first)
	}
}

// TestStandInGeneratorReadsNoClock is the other half of the determinism
// criterion, stated about the SOURCE: there is no clock in it. The
// positive control is a token the file genuinely contains, so a scan that
// silently read the wrong file cannot pass.
func TestStandInGeneratorReadsNoClock(t *testing.T) {
	// Comments are stripped first, for the reason design-contract.test.ts
	// strips them: the prose above the fixed instant explains what the
	// generator refuses to reach for, and a whole-file scan would be
	// satisfied by the explanation instead of by the code. The stripping
	// is a real Go parse, not a "//" search — see
	// TestStandInCommentStrippingIsAParseNotASearch for the two cases a
	// search gets wrong in OPPOSITE directions.
	source := standInSourceWithoutComments(t, "stand_in_data.go")
	if !strings.Contains(source, "func standInData(") {
		t.Fatal("positive control: the scanned file is not the generator, or the strip removed its declarations")
	}
	for _, forbidden := range []string{`"time"`, "time.Now", "math/rand", "os.Getenv", "rand.", "Unix()"} {
		if strings.Contains(source, forbidden) {
			t.Fatalf("the generator reaches for %q — the stand-in must be byte-deterministic on every run and every target", forbidden)
		}
	}
}

// TestStandInExcludesParamsAndReservedTokens pins the excluded roots.
// params keeps today's behaviour by ruling (an absent param stays a
// located BINDING_PATH_ABSENT), and AD-4's page/pages never acquire a
// data namespace.
func TestStandInExcludesParamsAndReservedTokens(t *testing.T) {
	elements := standInTextElement("e1", `{{customer.name}} on page {{page}} of {{pages}} for {{params.branch}} and {{upper(params.region)}}`)
	got := string(standInBytes(t, standInTemplate(t, elements)))
	if got != `{"customer":{"name":""}}` {
		t.Fatalf("stand-in document = %s, want only the one data path {\"customer\":{\"name\":\"\"}}", got)
	}
	for _, excluded := range []string{"params", "branch", "region", "page", "pages"} {
		if strings.Contains(got, excluded) {
			t.Fatalf("the excluded root %q reached the stand-in document: %s", excluded, got)
		}
	}
}

// TestStandInRefusesLeafAndBranchOnTheSamePath covers the other
// unsatisfiable shape: one path needs a value where another needs an
// object. No JSON document satisfies both, so the template is refused
// rather than silently losing one of the two bindings.
func TestStandInRefusesLeafAndBranchOnTheSamePath(t *testing.T) {
	elements := standInTextElement("e1", `{{customer}} and {{customer.name}}`)
	_, err := standInData(standInTemplate(t, elements))
	if err == nil {
		t.Fatal("StandInData produced a document where one path is both a value and an object")
	}
	if !strings.Contains(err.Error(), `"customer.name"`) || !strings.Contains(err.Error(), `"customer"`) {
		t.Fatalf("the refusal does not name both paths: %v", err)
	}
}

// TestStandInCoversSynthesizedFooterAggregates is the hole a text-only
// walk would leave: footerCellExprText synthesises count()/sum()/avg()
// at render time from bind and footerOf, and those expressions appear
// nowhere in the placeholder stream.
func TestStandInCoversSynthesizedFooterAggregates(t *testing.T) {
	table := `{"id": "e1", "type": "table", "x": 0, "y": 0, "bind": "ledger[]", "headerHeight": 12,
	  "style": {"fontFamily": "body", "fontSize": 9},
	  "columns": [
	    {"id": "e2", "label": "Count", "width": 100, "bind": "{{row.name}}", "footer": "count"},
	    {"id": "e3", "label": "Total", "width": 100, "bind": "{{formatNumber(row.amount, \"#,##0.00\")}}", "footer": "sum", "footerOf": "ledger.amount"}
	  ]}`
	tpl := standInTemplate(t, table)
	got := standInBytes(t, tpl)
	if string(got) != `{"ledger":[]}` {
		t.Fatalf("stand-in document = %s, want {\"ledger\":[]}", got)
	}
	if _, err := Render(tpl, Data(got), nil, testShippedFontSet()); err != nil {
		t.Fatalf("the synthesized-aggregate render failed: %v", err)
	}
}

// TestStandInBindingsFreeTemplateIsTheEmptyDocument covers the matrix's
// first row: a template with no bindings at all still gets a real,
// non-empty JSON document, because every byte channel into the engine
// refuses a zero-length input.
func TestStandInBindingsFreeTemplateIsTheEmptyDocument(t *testing.T) {
	tpl := standInTemplate(t, standInTextElement("e1", "Statement of account"))
	got := standInBytes(t, tpl)
	if string(got) != `{}` {
		t.Fatalf("stand-in document = %s, want {}", got)
	}
	if len(got) == 0 {
		t.Fatal("the stand-in document is zero-length — Engine.Render and Engine.PreviewIdentity both refuse that")
	}
	if _, err := Render(tpl, Data(got), nil, testShippedFontSet()); err != nil {
		t.Fatalf("the bindings-free render failed: %v", err)
	}
}

// TestStandInVisibleIfAloneShowsTheElement covers the visibleIf row: a
// path that only gates visibility resolves to true, because a layout
// preview exists to show the layout.
func TestStandInVisibleIfAloneShowsTheElement(t *testing.T) {
	elements := `{"id": "e1", "type": "rect", "x": 0, "y": 0, "width": 100, "height": 10, "visibleIf": "flags.showRule"}`
	tpl := standInTemplate(t, elements)
	got := standInBytes(t, tpl)
	if string(got) != `{"flags":{"showRule":true}}` {
		t.Fatalf("stand-in document = %s, want {\"flags\":{\"showRule\":true}}", got)
	}
	if _, err := Render(tpl, Data(got), nil, testShippedFontSet()); err != nil {
		t.Fatalf("the visibleIf render failed: %v", err)
	}
}

// TestStandInTypedOperandsTakeTheirOperatorsValue pins the two typed
// operand rows of the matrix as literal documents.
func TestStandInTypedOperandsTakeTheirOperatorsValue(t *testing.T) {
	number := standInBytes(t, standInTemplate(t, standInTextElement("e1", `{{formatNumber(invoice.total, "0.00")}}`)))
	if string(number) != `{"invoice":{"total":0}}` {
		t.Fatalf("formatNumber stand-in = %s, want {\"invoice\":{\"total\":0}}", number)
	}
	date := standInBytes(t, standInTemplate(t, standInTextElement("e1", `{{formatDate(invoice.issued, "yyyy-MM-dd")}}`)))
	if string(date) != `{"invoice":{"issued":"`+designer.StandInInstant+`"}}` {
		t.Fatalf("formatDate stand-in = %s, want the fixed instant %s", date, designer.StandInInstant)
	}
}

// standInSourceWithoutComments returns path's source with every comment
// removed, by PARSING it: parser.ParseFile without ParseComments drops
// comments entirely, and printer.Fprint renders what is left. A "//"
// search cannot do this correctly in either direction (see the test
// below), and this is a determinism guard, so it parses.
func standInSourceWithoutComments(t *testing.T, path string) string {
	t.Helper()
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	var out bytes.Buffer
	if err := printer.Fprint(&out, token.NewFileSet(), file); err != nil {
		t.Fatalf("print %s: %v", path, err)
	}
	return out.String()
}

// stripLineComments is the NAIVE stripper this file used to rely on. It
// is kept for exactly one purpose: to be the contrast arm below, so the
// hardening is demonstrated against the thing it replaced rather than
// asserted. Nothing else calls it.
func stripLineComments(source string) string {
	lines := strings.Split(source, "\n")
	for index, line := range lines {
		if at := strings.Index(line, "//"); at >= 0 {
			lines[index] = line[:at]
		}
	}
	return strings.Join(lines, "\n")
}

// TestStandInCommentStrippingIsAParseNotASearch proves the hardening
// with the two cases the naive stripper got wrong, in OPPOSITE
// directions:
//
//   - a /* */ block comment: the search leaves it, so a clock named only
//     in block-comment prose would RED the no-clock scan falsely, and
//     worse, prose can hide code from the scan the other way round;
//   - a "//" inside a STRING LITERAL: the search truncates the line
//     there, so any real code after it — including a clock call —
//     BECOMES INVISIBLE to the scan. That is the direction that matters:
//     it is how a determinism guard silently stops guarding.
func TestStandInCommentStrippingIsAParseNotASearch(t *testing.T) {
	synthetic := "package probe\n\n/* a block comment naming time.Now */\nfunc probe() string {\n\tmarker := \"a // b\" + \"tail\"\n\treturn marker\n}\n"
	path := filepath.Join(t.TempDir(), "probe.go")
	if err := os.WriteFile(path, []byte(synthetic), 0o600); err != nil {
		t.Fatalf("write probe: %v", err)
	}
	naive := stripLineComments(synthetic)
	parsed := standInSourceWithoutComments(t, path)

	if !strings.Contains(naive, "time.Now") {
		t.Fatal("contrast arm broken: the naive stripper was supposed to leave the block comment behind")
	}
	if strings.Contains(parsed, "time.Now") {
		t.Fatal("the parse-based stripper left a block comment's contents in the scanned source")
	}
	if strings.Contains(naive, `"tail"`) {
		t.Fatal("contrast arm broken: the naive stripper was supposed to truncate at the \"//\" inside the string literal")
	}
	if !strings.Contains(parsed, `"tail"`) {
		t.Fatal("the parse-based stripper dropped code following a \"//\" inside a string literal — the scan would not see a clock there")
	}
}

// TestStandInWalksAllThreeBands is patch 2's guard. Every other fixture
// here populates the content band alone, so reducing StandInData's band
// loop to Bands.Content left the whole package green — two thirds of the
// walk asserted by nothing. A bound path in the page header AND one in
// the page footer are required to appear in the document, and the page
// is required to render.
func TestStandInWalksAllThreeBands(t *testing.T) {
	header := standInBandTextElement("e1", 8, "Header {{report.title}}")
	content := standInTextElement("e2", "Body {{customer.name}}")
	footer := standInBandTextElement("e3", 8, "Footer {{report.reference}}")
	tpl, err := ParseTemplate([]byte(standInBandShell(header, content, footer)))
	if err != nil {
		t.Fatalf("presence precondition: the three-band fixture does not parse: %v", err)
	}
	got := standInBytes(t, tpl)
	if string(got) != `{"customer":{"name":""},"report":{"reference":"","title":""}}` {
		t.Fatalf("stand-in document = %s, want all three bands' paths", got)
	}
	if _, rerr := Render(tpl, Data(got), nil, testShippedFontSet()); rerr != nil {
		t.Fatalf("the three-band render failed: %v", rerr)
	}
}

// TestStandInRulesCoverEveryElementKind is the SECOND exhaustiveness
// gate. The element-kind set is AST-EXTRACTED from internal/template's
// own closedElementTypes literal — never restated here — so adding a
// sixth kind to the format reds this until the generator declares what
// that kind's data paths are.
func TestStandInRulesCoverEveryElementKind(t *testing.T) {
	formatKinds := closedElementTypesFromSource(t)
	ruleKinds := map[string]bool{}
	for _, kind := range slices.Sorted(maps.Keys(standInElementRules)) {
		ruleKinds[string(kind)] = true
	}
	for _, kind := range slices.Sorted(maps.Keys(formatKinds)) {
		if !ruleKinds[kind] {
			t.Errorf("%s: the format declares this element kind, but the stand-in generator has no rule for it", kind)
		}
	}
	for _, kind := range slices.Sorted(maps.Keys(ruleKinds)) {
		if !formatKinds[kind] {
			t.Errorf("%s: the stand-in generator has a rule for this, but the format declares no such element kind", kind)
		}
	}
	if len(formatKinds) == 0 || len(ruleKinds) == 0 {
		t.Fatalf("presence precondition: format kinds %d, generator rules %d — a zero on either side passes vacuously", len(formatKinds), len(ruleKinds))
	}
}

// closedElementTypesFromSource reads internal/template/closedsets.go and
// returns the keys of its closedElementTypes composite literal. It is an
// AST walk rather than a second literal for the same reason
// table_derivational_test.go's switch scan is: a restated set agrees
// with itself forever.
func closedElementTypesFromSource(t *testing.T) map[string]bool {
	t.Helper()
	const path = "internal/template/closedsets.go"
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
	if err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	kinds := map[string]bool{}
	ast.Inspect(file, func(node ast.Node) bool {
		spec, ok := node.(*ast.ValueSpec)
		if !ok || len(spec.Names) != 1 || spec.Names[0].Name != "closedElementTypes" || len(spec.Values) != 1 {
			return true
		}
		literal, ok := spec.Values[0].(*ast.CompositeLit)
		if !ok {
			return true
		}
		for _, element := range literal.Elts {
			pair, ok := element.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			key, ok := pair.Key.(*ast.BasicLit)
			if !ok || key.Kind != token.STRING {
				continue
			}
			unquoted, uerr := strconv.Unquote(key.Value)
			if uerr != nil {
				t.Fatalf("unquote %s: %v", key.Value, uerr)
			}
			kinds[unquoted] = true
		}
		return false
	})
	return kinds
}

// TestStandInSetHasOneBitPerValue ties standInSetBits to the TYPE rather
// than to its own declaration. The compile-time constant in the
// generator ties the MEMBER COUNT to standInSetBits; without this, both
// could be edited to agree with each other while the type stayed narrow.
func TestStandInSetHasOneBitPerValue(t *testing.T) {
	// The shifts are through VARIABLES so they are evaluated at run time
	// against the real type width; as constant expressions the compiler
	// would reject the overflow instead of demonstrating it.
	one, top, past := standInSet(1), uint(standInSetBits-1), uint(standInSetBits)
	if one<<top == 0 {
		t.Fatalf("standInSet is narrower than standInSetBits (%d): its top bit truncates to zero", standInSetBits)
	}
	if one<<past != 0 {
		t.Fatalf("standInSet is wider than standInSetBits (%d): the compile-time member check bounds the wrong number", standInSetBits)
	}
	if standInValueCount > standInSetBits {
		t.Fatalf("standInValueCount %d exceeds standInSetBits %d", standInValueCount, standInSetBits)
	}
	// Every declared member owns a distinct, in-range bit.
	seen := map[standInSet]bool{}
	for value := standInEmptyString; value <= standInEmptyCollection; value++ {
		bit := standInSetOf(value)
		if bit == 0 || seen[bit] {
			t.Fatalf("standInValue %d has no distinct bit in standInSet", value)
		}
		seen[bit] = true
	}
	if len(seen) != standInValueCount {
		t.Fatalf("bits %d, declared members %d", len(seen), standInValueCount)
	}
}

// TestStandInRefusesBeyondItsDeclaredBounds is patch 6's guard: both
// limits were asserted by nothing, so deleting either check left the
// package green. engine.worker.ts decodes a non-render byte response
// with NO transport bound, so these two are the only bound there is.
func TestStandInRefusesBeyondItsDeclaredBounds(t *testing.T) {
	t.Run("path count", func(t *testing.T) {
		var builder strings.Builder
		for index := 0; index <= designer.MaxStandInDataPaths; index++ {
			fmt.Fprintf(&builder, "{{p%d}} ", index)
		}
		_, err := standInData(standInTemplate(t, standInTextElement("e1", builder.String())))
		if err == nil {
			t.Fatalf("StandInData accepted more than %d paths", designer.MaxStandInDataPaths)
		}
		if !strings.Contains(err.Error(), fmt.Sprintf("more than %d data paths", designer.MaxStandInDataPaths)) {
			t.Fatalf("the refusal does not name the path limit: %v", err)
		}
	})

	t.Run("document bytes", func(t *testing.T) {
		// Few enough paths to clear the path limit, long enough names to
		// break the byte limit.
		const names = 450
		const width = 600
		var builder strings.Builder
		for index := 0; index < names; index++ {
			fmt.Fprintf(&builder, "{{%s%d}} ", strings.Repeat("a", width), index)
		}
		if names > designer.MaxStandInDataPaths {
			t.Fatalf("presence precondition: %d paths would trip the path limit first", names)
		}
		_, err := standInData(standInTemplate(t, standInTextElement("e1", builder.String())))
		if err == nil {
			t.Fatalf("StandInData accepted a document beyond %d bytes", designer.MaxStandInDataBytes)
		}
		if !strings.Contains(err.Error(), fmt.Sprintf("exceeds the %d-byte limit", designer.MaxStandInDataBytes)) {
			t.Fatalf("the refusal does not name the byte limit: %v", err)
		}
	})
}

// standInBandTextElement is a text element sized to fit a 20pt band.
func standInBandTextElement(id string, size int, value string) string {
	return fmt.Sprintf(`{"id": %q, "type": "text", "x": 0, "y": 0, "width": 460, "height": 12, "value": %q, "style": {"fontFamily": "body", "fontSize": %d}}`, id, value, size)
}

func standInReadFile(t *testing.T, path string) []byte {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return raw
}
