package template

// This file holds the trap and passthrough fixtures the round-trip
// property tests (roundtrip_test.go) run over. Each is asserted
// canonical by TestP3FixturesAreCanonical before being trusted for
// anything else.

// unknownKeysFixture carries an unknown key at every nesting level this
// story's finisher review (Finding 2, D-1.4.9 OWNER) confirmed must
// accept opaque passthrough: top level, inside a band, inside an
// element, inside a column, inside style, inside page, inside
// page.margin, inside style.padding, inside style.border, and inside
// one assets[entry] object — ten of the document's eleven object
// levels. (bands itself is the deliberate eleventh, closed exception —
// see Bands' doc comment in model.go and TestBandsRejectsAnUnknownKey
// below.) Also carries a non-ASCII top-level key ("\u00e4NonAsciiOrderMarker")
// alongside an ASCII one ("zzAsciiOrderMarker") so AC18's byte-order key
// sort is asserted rather than holding "by coincidence over an
// all-ASCII corpus" (Finding 11): byte-order sorts "zz..." before
// "\u00e4..." (0x7A < 0xC3), which a locale-aware collation would not.
// AC26 (D-1.8.1 + D-1.8.3): the key here was 64x'b' at baseline, and the
// data decoded to a single byte 'f' — neither a valid key (AC6) nor a
// valid image (AC9). Rebuilt on a real, supported, non-alpha 1x1
// grayscale PNG under its real SHA-256 key
// (541581d3ab4d47c46ce5bcfbe86f9e9369f425b41df11decff572d259fa22c65,
// generated by Go's image/png encoder and independently cross-checked
// with Python's hashlib/base64, per D-1.8.7's discipline). AC26a: this
// changes ONLY the key and data — futureAssetEntryKey stays inside the
// asset entry, and unknown-key passthrough at this nesting level is
// still exercised exactly as before.
var unknownKeysFixture = []byte(`{
  "assets": {
    "541581d3ab4d47c46ce5bcfbe86f9e9369f425b41df11decff572d259fa22c65": {
      "data": [
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAADklEQVR4nGJqAAQAAP//AIYAg0ye",
        "IEsAAAAASUVORK5CYII="
      ],
      "futureAssetEntryKey": true,
      "mediaType": "image/png"
    }
  },
  "bands": {
    "content": {
      "elements": [
        {
          "as": "row",
          "bind": "items[]",
          "columns": [
            {
              "bind": "{{row.n}}",
              "futureColumnKey": true,
              "id": "e2",
              "label": "N",
              "width": 40
            }
          ],
          "futureElementKey": [
            1,
            2
          ],
          "headerHeight": 14,
          "id": "e1",
          "style": {
            "border": {
              "edges": [
                "bottom"
              ],
              "futureBorderKey": true
            },
            "fontSize": 9,
            "futureStyleKey": "z",
            "padding": {
              "futurePaddingKey": true,
              "left": 3
            }
          },
          "type": "table",
          "x": 0,
          "y": 0
        }
      ],
      "futureBandKey": 1
    },
    "pageFooter": {
      "elements": [],
      "height": 20
    },
    "pageHeader": {
      "elements": [],
      "height": 20
    }
  },
  "fonts": {},
  "futureTopLevelKey": {
    "nested": [
      1,
      2,
      "th ท 中"
    ]
  },
  "locale": "en",
  "nextId": 3,
  "page": {
    "futurePageKey": true,
    "margin": {
      "bottom": 36,
      "futureMarginKey": true,
      "left": 36,
      "right": 36,
      "top": 36
    },
    "orientation": "portrait",
    "size": "A4"
  },
  "utcOffset": "+00:00",
  "version": "1.0",
  "zzAsciiOrderMarker": true,
  "äNonAsciiOrderMarker": true
}
`)

// htmlEscapeTrapFixture carries '<', '>' and '&' in a text value — AC19:
// HTML escaping must be OFF, so these appear literally, never as
// entity-escaped forms.
var htmlEscapeTrapFixture = []byte(`{
  "assets": {},
  "bands": {
    "content": {
      "elements": []
    },
    "pageFooter": {
      "elements": [],
      "height": 20
    },
    "pageHeader": {
      "elements": [
        {
          "height": 14,
          "id": "e1",
          "type": "text",
          "value": "a<b>c&d",
          "width": 100,
          "x": 0,
          "y": 0
        }
      ],
      "height": 20
    }
  },
  "fonts": {},
  "locale": "en",
  "nextId": 2,
  "page": {
    "margin": {
      "bottom": 36,
      "left": 36,
      "right": 36,
      "top": 36
    },
    "orientation": "portrait",
    "size": "A4"
  },
  "utcOffset": "+00:00",
  "version": "1.0"
}
`)

// utf8TrapFixture carries Thai and CJK text — AC20: UTF-8 is emitted
// literally, no \uXXXX escape above 0x1F.
var utf8TrapFixture = []byte(`{
  "assets": {},
  "bands": {
    "content": {
      "elements": []
    },
    "pageFooter": {
      "elements": [],
      "height": 20
    },
    "pageHeader": {
      "elements": [
        {
          "height": 14,
          "id": "e1",
          "type": "text",
          "value": "ใบแจ้งหนี้ 中文 日本語",
          "width": 200,
          "x": 0,
          "y": 0
        }
      ],
      "height": 20
    }
  },
  "fonts": {},
  "locale": "th",
  "nextId": 2,
  "page": {
    "margin": {
      "bottom": 36,
      "left": 36,
      "right": 36,
      "top": 36
    },
    "orientation": "portrait",
    "size": "A4"
  },
  "utcOffset": "+07:00",
  "version": "1.0"
}
`)

// minimalEscapeTrapFixture carries '"', '\\', a control character below
// 0x20 (newline) and '/' — AC21: only '"', '\\' and sub-0x20 controls
// are escaped; '/' is never escaped.
var minimalEscapeTrapFixture = []byte("{\n  \"assets\": {},\n  \"bands\": {\n    \"content\": {\n      \"elements\": []\n    },\n    \"pageFooter\": {\n      \"elements\": [],\n      \"height\": 20\n    },\n    \"pageHeader\": {\n      \"elements\": [\n        {\n          \"height\": 14,\n          \"id\": \"e1\",\n          \"type\": \"text\",\n          \"value\": \"a \\\"quoted\\\" \\\\ line1\\nline2 a/b\",\n          \"width\": 200,\n          \"x\": 0,\n          \"y\": 0\n        }\n      ],\n      \"height\": 20\n    }\n  },\n  \"fonts\": {},\n  \"locale\": \"en\",\n  \"nextId\": 2,\n  \"page\": {\n    \"margin\": {\n      \"bottom\": 36,\n      \"left\": 36,\n      \"right\": 36,\n      \"top\": 36\n    },\n    \"orientation\": \"portrait\",\n    \"size\": \"A4\"\n  },\n  \"utcOffset\": \"+00:00\",\n  \"version\": \"1.0\"\n}\n")

// maximalFixture exercises every one of the keys the serializer can
// emit (58 as of SPEC-table-rules, which added the table-level "rules"
// block with its own "between" array and the table-level "minHeight"
// floor; it was 55 at Story 7.7, which added the element-level
// "keepTogether" tag; it was 52 at Story 2.4, which added the
// document-level "unbreakableValues" declaration, and lineSpacing,
// color and keepTogether have been added since) (D-1.4.15's "maximal document"; this story's finisher review,
// Findings 1 and 8): every element kind, every style/border/padding
// field, the footer/footerOf/footerFormat trio, an image asset, and
// visibleIf. It is both a canonicalFixtures entry (closing Finding 8's
// round-trip coverage gap) and the runtime side of drift_test.go's
// behavioural set-equality assertion (D-1.4.15).
// AC26 (D-1.8.1 + D-1.8.3): the key here was 64x'a' at baseline and the
// data was a TRUNCATED PNG (first 60 base64 chars of a 70-byte PNG) —
// neither a valid key nor a valid image. Rebuilt on a real, supported,
// NON-SQUARE 3x2 8-bit RGB PNG (AC27a: non-square, so the fixture can
// distinguish AC13's two binding-axis branches) under its real SHA-256
// key (5a05ad01e89c143b7061b0c93450566568d38a23da9b9c5c9dfe449016433078,
// generated by Go's image/png encoder and independently cross-checked
// with Python's hashlib/base64). AC26a: this changes only the key,
// data and the element's "asset" reference below — every other field
// this fixture exercises is unchanged.
//
// Story 8.3 added a SECOND asset: a font asset carrying the optional
// `font` record, so `font`/`family`/`licence`/`source` are keys this
// fixture actually EMITS rather than keys only the AST can see
// (TestDriftASTMatchesRuntimeEmission compares those two sets both ways
// and is the reason this fixture, not another, had to grow).
//
// Its bytes are a hand-built 156-byte sfnt — a version tag, a
// three-entry table directory and three 32-byte tables — under its real
// SHA-256 key,
// which is all `mediaType: "font/ttf"` obliges the loader to find: the
// load-time check is STRUCTURAL (checkSfnt), not a face parse. It is a
// fixture and not a face, and its `font.source` says so in the file. A
// real face would add ~47 KB to a test fixture to prove nothing this
// one does not.
//
// It is NOT referenced by a chain entry, deliberately. That an
// unreferenced font asset does NOT raise the version is itself the rule
// (D-1.4.13), and it is asserted directly in linespacing_test.go rather
// than resting on this fixture.
//
// ⚠ THE FIXTURE CARRIES `embedFonts: false`, AND IT IS A COVERAGE CHOICE
// RATHER THAN A STATEMENT ABOUT THIS DOCUMENT. maximalFixture exists to
// exercise EVERY key the serializer can emit — TestDriftASTMatchesRuntimeEmission
// compares the AST's key set against what this fixture actually emits at
// runtime, in both directions — and `embedFonts` is written ONLY when it is
// false, because true is the default and is written as an absent key. So
// `false` is the only value that makes the key appear at all, and appearing is
// the fixture's whole job.
//
// THE CONSEQUENCE IS WORTH KNOWING BEFORE THE SETTING GAINS BEHAVIOUR. Nothing
// reads the field today, so this changes nothing for any test using the
// fixture. When a later story makes the setting behavioural, a test that uses
// maximalFixture and cares whether faces are embedded must say so itself —
// this document declines, and it declines for a serializer-coverage reason,
// not because a document that carries a font asset ought to.

// ⚠ THE FIXTURE DECLARES 2.0 SINCE STORY 11.2, AND ITS CHAIN IS WHY. The
// story added two genuinely new serialized keys — `face` and
// `boldItalic` — so the middle chain entry is written in the OBJECT form
// that carries them, and an object-form entry raises the document to 2.0
// exactly as an embedded-face entry does (version.go's fontsRequireMajor
// reads one shared predicate for both). The version moved with the
// fixture's own content, which is the rule this file demonstrates rather
// than an exception to it. The unreferenced font asset above is still
// unreferenced and still raises nothing on its own.
var maximalFixture = []byte(`{
  "assets": {
    "5a05ad01e89c143b7061b0c93450566568d38a23da9b9c5c9dfe449016433078": {
      "data": [
        "iVBORw0KGgoAAAANSUhEUgAAAAMAAAACCAIAAAASFvFNAAAAGElEQVR42mL6z8DAAMZMEOo/AwMg",
        "AAD//zwUBf/NjsW5AAAAAElFTkSuQmCC"
      ],
      "mediaType": "image/png"
    },
    "cbd7a24e64e08aba9da4edd9343b9eaa629e7c26e722eedf68fd5efe217dbedc": {
      "data": [
        "AAEAAAADACAABAAQY21hcAAAAAAAAAA8AAAAIGdseWYAAAAAAAAAXAAAACBoZWFkAAAAAAAAAHwA",
        "AAAgQ01BUERBVEFDTUFQREFUQUNNQVBEQVRBQ01BUERBVEFHTFlGREFUQUdMWUZEQVRBR0xZRkRB",
        "VEFHTFlGREFUQUhFQUREQVRBSEVBRERBVEFIRUFEREFUQUhFQUREQVRB"
      ],
      "font": {
        "authorAcknowledged": true,
        "copyright": "Copyright 2026 The Folio Fixture Authors",
        "family": "Maximal Sans",
        "licence": "SIL Open Font License 1.1",
        "licenceText": "This fixture face is licensed under the SIL Open Font License, Version 1.1.",
        "source": "hand-built 156-byte sfnt, tools/none — a fixture, not a face",
        "style": "Regular"
      },
      "mediaType": "font/ttf"
    }
  },
  "bands": {
    "content": {
      "elements": [
        {
          "altRowBackground": "#EEEEEE",
          "as": "transaction",
          "bind": "transactions[]",
          "columns": [
            {
              "align": "left",
              "bind": "{{transaction.date}}",
              "headerAlign": "center",
              "id": "e3",
              "label": "Date",
              "width": 80
            },
            {
              "align": "right",
              "bind": "{{formatNumber(transaction.amount, \"#,##0.00\")}}",
              "footer": "sum",
              "footerFormat": "#,##0.00",
              "footerOf": "transactions.amount",
              "id": "e4",
              "label": "Amount",
              "width": 90
            }
          ],
          "headerHeight": 16,
          "headerStyle": {
            "align": "center",
            "background": "#DDDDDD",
            "border": {
              "color": "#333333",
              "edges": [
                "bottom"
              ],
              "width": 0.75
            },
            "fontFamily": "body",
            "fontSize": 9,
            "lineSpacing": 1.25,
            "padding": {
              "bottom": 3,
              "left": 3,
              "right": 3,
              "top": 3
            },
            "valign": "middle"
          },
          "id": "e1",
          "minHeight": 240,
          "rules": {
            "between": [
              "columns",
              "rows"
            ],
            "color": "#666666",
            "width": 0.25
          },
          "style": {
            "align": "left",
            "background": "#F1F4F7",
            "bold": true,
            "border": {
              "color": "#000000",
              "edges": [
                "bottom",
                "top"
              ],
              "width": 0.5
            },
            "fontFamily": "body",
            "fontSize": 8,
            "italic": true,
            "lineSpacing": 0.875,
            "padding": {
              "bottom": 2,
              "left": 3,
              "right": 3,
              "top": 2
            },
            "valign": "top"
          },
          "type": "table",
          "visibleIf": "customer.hasTransactions",
          "x": 0,
          "y": 0
        },
        {
          "asset": "5a05ad01e89c143b7061b0c93450566568d38a23da9b9c5c9dfe449016433078",
          "height": 60,
          "id": "e5",
          "keepTogether": "signature",
          "type": "image",
          "width": 100,
          "x": 0,
          "y": 200
        },
        {
          "height": 1,
          "id": "e6",
          "keepTogether": "signature",
          "style": {
            "background": "#000000"
          },
          "type": "rect",
          "width": 500,
          "x": 0,
          "y": 300
        },
        {
          "errorCorrection": "Q",
          "height": 72,
          "id": "e8",
          "type": "qrcode",
          "value": "INV-{{customer.name}}",
          "width": 72,
          "x": 400,
          "y": 200
        }
      ],
      "sectionBreak": 600,
      "sectionBreakAnchor": false
    },
    "pageFooter": {
      "elements": [
        {
          "height": 10,
          "id": "e7",
          "style": {
            "align": "center",
            "fontSize": 7
          },
          "type": "text",
          "value": "Page {{page}} of {{pages}}",
          "width": 523,
          "x": 0,
          "y": 8
        }
      ],
      "height": 30
    },
    "pageHeader": {
      "elements": [
        {
          "height": 16,
          "id": "e2",
          "style": {
            "bold": true,
            "fontSize": 12
          },
          "type": "text",
          "value": "Statement for {{customer.name}}",
          "width": 400,
          "x": 0,
          "y": 10
        }
      ],
      "height": 60
    }
  },
  "embedFonts": false,
  "fonts": {
    "body": [
      "Noto Sans",
      {
        "bold": "Noto Sans Thai Bold",
        "boldItalic": "Noto Sans Thai Bold Italic",
        "face": "Noto Sans Thai",
        "italic": "Noto Sans Thai Italic"
      },
      "Noto Sans SC"
    ]
  },
  "locale": "th",
  "nextId": 9,
  "page": {
    "margin": {
      "bottom": 36,
      "left": 36,
      "right": 36,
      "top": 36
    },
    "orientation": "portrait",
    "size": "A4"
  },
  "unbreakableValues": [
    "customer.name"
  ],
  "utcOffset": "+07:00",
  "version": "4.1"
}
`)

// nullFieldFixture carries an explicit JSON `null` on two Presence-typed
// fields (element.style, element.visibleIf) — D-1.4.16, this story's
// finisher review Finding 6 (Major): no canonical fixture previously
// carried an explicit null, so P1/P2/P3 never exercised that path as a
// fixed point. See TestPresenceThreePolarity's "serializes-differently"
// subtest (presence_test.go) for the direct absent/null/present
// serialization-distinctness assertion this fixture complements.
var nullFieldFixture = []byte(`{
  "assets": {},
  "bands": {
    "content": {
      "elements": []
    },
    "pageFooter": {
      "elements": [],
      "height": 20
    },
    "pageHeader": {
      "elements": [
        {
          "height": 14,
          "id": "e1",
          "style": null,
          "type": "text",
          "value": "v",
          "visibleIf": null,
          "width": 100,
          "x": 0,
          "y": 0
        }
      ],
      "height": 20
    }
  },
  "fonts": {},
  "locale": "en",
  "nextId": 2,
  "page": {
    "margin": {
      "bottom": 36,
      "left": 36,
      "right": 36,
      "top": 36
    },
    "orientation": "portrait",
    "size": "A4"
  },
  "utcOffset": "+00:00",
  "version": "1.0"
}
`)
